# Generated by Django 5.0.6 on 2024-06-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('3', ' 3️⃣'), ('7', ' 7️⃣'), ('9', ' 9️⃣'), ('2', ' 2️⃣'), ('4', ' 4️⃣'), ('1', ' 1️⃣'), ('8', ' 8️⃣'), ('6', ' 6️⃣'), ('10', '🔟'), ('5', ' 5️⃣')], max_length=2),
        ),
    ]
