# Generated by Django 5.0.6 on 2024-06-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todo_time_alter_todo_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date',
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('7', ' 7️⃣'), ('8', ' 8️⃣'), ('1', ' 1️⃣'), ('5', ' 5️⃣'), ('6', ' 6️⃣'), ('2', ' 2️⃣'), ('10', '🔟'), ('3', ' 3️⃣'), ('4', ' 4️⃣'), ('9', ' 9️⃣')], max_length=2),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('p', 'PENDING'), ('c', 'COMPLETED')], max_length=2),
        ),
    ]
