# Generated by Django 5.0.6 on 2024-06-25 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_remove_todo_date_alter_todo_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('9', ' 9️⃣'), ('4', ' 4️⃣'), ('2', ' 2️⃣'), ('8', ' 8️⃣'), ('3', ' 3️⃣'), ('6', ' 6️⃣'), ('7', ' 7️⃣'), ('10', '🔟'), ('5', ' 5️⃣'), ('1', ' 1️⃣')], max_length=2),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('c', 'COMPLETED'), ('p', 'PENDING')], max_length=2),
        ),
    ]
