# Generated by Django 5.0.6 on 2024-06-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_todo_date_alter_todo_priority_alter_todo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='time',
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('3', ' 3️⃣'), ('1', ' 1️⃣'), ('6', ' 6️⃣'), ('8', ' 8️⃣'), ('4', ' 4️⃣'), ('7', ' 7️⃣'), ('9', ' 9️⃣'), ('2', ' 2️⃣'), ('5', ' 5️⃣'), ('10', '🔟')], max_length=2),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('p', 'PENDING'), ('c', 'COMPLETED')], max_length=2),
        ),
    ]
